var express = require('express');
var router = express.Router();
var fs = require('fs');

var breeds = [
  {name: "Labrador Retriever", description: "Few breeds so richly deserve their popularity as the Labrador retriever. Devoted, obedient and amiable, the Lab is good with children, other dogs and other pets. He will be a calm house dog, playful yard dog and intense field dog, all on the same day. He is eager to please, enjoys learning and excels in obedience. He is a powerful breed that loves to swim and retrieve. He needs daily physical and mental challenges to keep him occupied, however; a bored Lab can get into trouble.", image: "http://4.bp.blogspot.com/-0ko7V5wM5xw/UX8P0PiAOJI/AAAAAAAACFg/Ckhj43HwF_Y/s1600/Labrador_Retriever_Boomer_IMG_0030.jpg", hypoallergenic: "No", lifespan: "10-12 years"},
  {name: "German Shepherd", description: "Among the most intelligent of breeds, the German Shepherd Dog is so intent on his mission whatever that may be and he is virtually unsurpassed in working versatility. He is utterly devoted and faithful. He is usually good with other pets.", image: "http://cdn2.milled.com/contents/2014-06-09/GJLbJ4Cm4HEFw3Bi/mL_xjtMv4R5zAScJ.jpg", hypoallergenic: "No", lifespan: "10-12 years"},
  {name: "Golden Retriever", description: "Everybody's friend, the golden retriever is known for her devoted and obedient nature as a family companion. She is an apt sporting retriever as well and yearns for a day in the field. Ignoring her active nature and powerful physique can lead to behavior problems, and she needs daily physical and mental exercise. She tends to be overly exuberant and boisterous, and her enthusiasm for everything often distracts her during training; however, she is eager to please and enjoys learning. The golden's achievements in competitive obedience are remarkable. She especially enjoys games that involve retrieving and loves to carry items in her mouth.", image: "http://41.media.tumblr.com/7b259fc8fc2fc2d92006c1d88aee73d2/tumblr_nsto2c9ra11u0yf4mo1_400.jpg", hypoallergenic: "No", lifespan: "10-13 years"},
  {name: "Bulldog", description: "Despite his sourmug the Bulldog is jovial, comical and amiable, among the most docile and mellow of dogs. He is willing to please, although he retains a stubborn streak. The bulldog is very good with children. Most are moderately friendly toward strangers. The breed is quite good with other pets.", image: "https://s2.graphiq.com/sites/default/files/465/media/images/t2/Bulldog_4924920.jpg", hypoallergenic: "No", lifespan: "8-10 years"},
  {name: "Beagle", description: "One of the most amiable hounds, the Beagle was bred as a pack hunter and needs companionship, whether human or canine. He loves to explore the outdoors and is an enthusiastic trailer. Given adequate exercise, he is a calm, tractable house pet. He is an excellent child's dog, gentle, incredibly tolerant and always ready to join in a game or an adventure. He is an independent breed, however, and may run off if a trail beckons. He barks and howls.", image: "http://www.askavetquestion.com/news/wp-content/uploads/2011/02/beagle.png", hypoallergenic: "No", lifespan: "12-15 years"},
  {name: "French Bulldog", description: "The French Bulldog is a clown in a lap dog. He enjoys playing and entertaining his family, as well as cuddling and snoozing with his favorite person. He is amiable, sweet, companionable and willing to please.", image: "http://www.petyourdog.com/uploads/dog_pictures/large/1392625476~Bulldog-puppy-in-the-morning.jpg", hypoallergenic: "No", lifespan: "9-11 years"},
  {name: "Yorkshire Terrier", description: "The Yorkshire Terrier seems oblivious of her small size, ever eager for adventure and trouble. She is busy, inquisitive, bold, stubborn. Although some tend to bark a lot, she can easily be taught not to do so.", image: "http://www.i-heart-pets.com/wp-content/uploads/2014/08/yorkshire-terrier-10.jpg", hypoallergenic: "Yes", lifespan: "14-16 years"},
  {name: "Poodle", description: "Among the very smartest and most obedient of dogs, the standard Poodle combines playful exuberance with a zest for life's adventures. He retains his hunting heritage and loves to run, swim and retrieve. He gets along well with everyone, although he can be somewhat reserved with strangers. He is excellent with children.", image: "https://c2.staticflickr.com/8/7335/10529115303_b32def8c24_b.jpg", hypoallergenic: "Yes", lifespan: "10-13 years"},
  {name: "Rottweiler", description: "Confident, bold, alert and imposing, the Rottweiler is a popular choice for his ability to protect. As befitting his self-assured nature, he tends to be headstrong and stubborn and is often domineering. He can be reserved, often wary, toward strangers. He may be overly protective if he perceives that his family is being threatened, and he may also attempt to \"herd\" children. This is a powerful breed that needs socialization, consistent training and daily exercise to be the best he can be , a loyal family member and guardian.", image: "https://scontent.cdninstagram.com/hphotos-xaf1/t51.2885-15/s640x640/sh0.08/e35/11809849_798005126963382_724770429_n.jpg", hypoallergenic: "No", lifespan: "8-11 years"},
  {name: "Boxer", description: "The boxer is playful, exuberant, inquisitive, attentive, demonstrative, devoted and outgoing; he is a perfect companion for an active family. He can be stubborn, but he is sensitive and responsive to commands. He is generally good with other household dogs and pets.", image: "http://dingo.care2.com/pictures/greenliving/uploads/2013/10/boxer-pant.jpg", hypoallergenic: "No", lifespan: "8-10 years"},
  {name: "German Shorthaired Pointer", description: "The German shorthaired pointer's idea of heaven is a day hunting in the field and an evening curled up by his family's side. This is an active dog that can become frustrated and \"creative\" if not given ample daily exercise, both mental and physical. He is a devoted family pet, although at times he is overly boisterous for small children. Because part of his heritage includes hunting mammals, some may not be good with small pets. He is a sensitive breed, responsive to gentle training. Some can whine or bark a lot.", image: "https://s-media-cache-ak0.pinimg.com/736x/8c/ef/01/8cef011dde975d1cf12335f514b80b11.jpg", hypoallergenic: "No", lifespan: "12-14 years"},
  {name: "Siberian Husky", description: "Fun-loving, adventurous, alert, independent, clever, stubborn, mischievous and obstinate, all describe the Siberian husky. This breed loves to run and will roam if given the chance. He is generally good with other household dogs. In fact, he is a very social dog that must have human or canine companionship. He may chase strange cats or livestock. Some howl, dig and chew.", image: "http://2.bp.blogspot.com/-MHLds3-q-VU/VgFXdSiVtmI/AAAAAAAA538/CzJVcracluM/s640/20150421-happy-husky.jpg", hypoallergenic: "No", lifespan: "11-13 years"},
  {name: "Dachshund", description: "The Dachshund is bold, curious and always up for adventure. He likes to hunt and dig, tracking by scent and going to ground after game. He is independent but will join in his family's activities whenever given a chance. He is good with children in his own family. Some bark. The longhaired variety may be quieter and less terrier-like; the wires may be more outgoing. Some miniatures are more prone to be timid.", image: "http://www.tehcute.com/pics/201111/smiling-dachshund.jpg", hypoallergenic: "No", lifespan: "12-14 years"},
  {name: "Doberman Pinscher", description: "The Doberman pinscher is an intelligent capable guardian, ever on the alert and ready to protect her family or home. She is also a loyal and adventurous companion. She likes to be mentally challenged and is a gifted obedience pupil. She is sensitive and very responsive to her family's wishes, though some can be domineering. She is generally reserved with strangers.", image: "https://s-media-cache-ak0.pinimg.com/736x/aa/fe/28/aafe28fdd474e6c48bb15d6532495e49.jpg", hypoallergenic: "No", lifespan: "10-12 years"},
  {name: "Great Dane", description: "The Great Dane is gentle, loving, easygoing and sensitive. She is generally good with children (although her friendly overtures may overwhelm a small child) and usually friendly toward other dogs and pets. She is powerful but sensitive and responsive to training. She makes a pleasant, well-mannered family companion.", image: "http://i.imgur.com/U4qRN.jpg", hypoallergenic: "No", lifespan: "6-8 years"}
];

// {name: "", description: "", image: "", hypoallergenic: "", lifespan: ""}

router.get('/', function(request, response) {
  response.send(breeds);
});


module.exports = router;